# Generated by Django 4.0.6 on 2022-08-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About user'},
        ),
    ]
